protected/models/ActiveQuery.php
<?php

namespace app\models;

class ActiveQuery extends \yii\db\ActiveQuery {

	public function getTableName() {
		$modelName = $this->modelClass;
		return $modelName::tableName();
	}

	public function resetScopes() {
		$this->where = '';
		return $this;
	}
}

protected/models/ActiveRecord.php
<?php

namespace app\models;

class ActiveRecord extends \yii\db\ActiveRecord {

}

protected/models/ContactForm.php
<?php

namespace app\models;

use yii\base\Model;
use \Yii;

/**
 * @property int    $id
 * @property string $content
 * @property string $url
 * @property bool   $active
 */
class ContactForm extends Model {

	public $name;
	public $email;
	public $body;
	public $verifyCode;

	public function rules() {
		return [
			// name, email, subject and body are required
			[['name', 'email', 'body'], 'required'],
			// email has to be a valid email address
			['email', 'email'],
			// verifyCode needs to be entered correctly
			['verifyCode', 'captcha', 'captchaAction' => 'main/captcha'],
		];
	}

	/**
	 * @return array customized attribute labels
	 */
	public function attributeLabels() {
		return [
			'name'       => 'Ваше имя',
			'email'      => 'Электронный адрес',
			'body'       => 'Сообщение',
			'verifyCode' => 'Проверочный код',
		];
	}

	/**
	 * Sends an email to the specified email address using the information collected by this model.
	 * @return boolean whether the model passes validation
	 */
	public function sendAdminEmail() {
		if ($this->validate()) {
			return Yii::$app->mailer->compose()
				->setTo([Yii::$app->params['adminEmail'], Yii::$app->params['adminEmail2']])
				->setFrom([$this->email => $this->name])
				->setSubject('Запрос из формы обратной связи')
				->setTextBody($this->body)
				->send();
		} else {
			return false;
		}
	}
}

protected/models/Page.php
<?php

namespace app\models;

/**
 * @property int    $id
 * @property string $content
 * @property string $url
 * @property bool   $active
 */
class Page extends ActiveRecord {

	/**
	 * @return PageQuery
	 */
	public static function find() {
		return (new PageQuery(get_called_class()))->active();
	}
}

class PageQuery extends ActiveQuery {

	public function active() {
		$this->andWhere('active = 1');
		return $this;
	}

	public function byUrl($url) {
		$this->andWhere('url = :url', [':url' => $url]);
		return $this;
	}
}

protected/models/Portfolio.php
<?php

namespace app\models;

/**
 * @property int    $id
 * @property string $title
 * @property string $url
 * @property string $image
 * @property string $teaser
 * @property string $desc
 * @property bool   $active
 */
class Portfolio extends ActiveRecord {

	/**
	 * @return ActiveQuery
	 */
	public static function find() {
		return (new PortfolioQuery(get_called_class()))->active();
	}

	public function rules() {
		return [
			[['title', 'url'], 'required'],
			[['desc', 'teaser', 'active'], 'safe'],
		];
	}

	/**
	 * @return self
	 */
	public function getNext() {
		$next = $this->find()->where(['>', 'id', $this->id])->one();
		return $next;
	}

	/**
	 * @return self
	 */
	public function getPrev() {
		$prev = $this->find()->where(['<', 'id', $this->id])->orderBy('id DESC')->one();
		return $prev;
	}
}

class PortfolioQuery extends ActiveQuery {

	public function active() {
		$this->andWhere('active = 1');
		return $this;
	}
}

protected/controllers/AjaxController.php
<?php

namespace app\controllers;

use app\models\Portfolio;
use Yii;
use yii\helpers\Url;

class AjaxController extends BaseController {

	public function actionPortfolioItem($id) {
		$portfolio = Portfolio::findOne($id);
		$data = $portfolio->attributes;
		unset($data['active'], $data['created']);
		$data['portfolioUrl'] = Url::to(['ajax/portfolio-item', 'id' => $id]);

		$data['prevItem'] = $data['nextItem'] = null;
		if ($prev = $portfolio->getPrev()) {
			$data['prevItem'] = Url::to(['ajax/portfolio-item', 'id' => $prev->id]);
		}
		if ($next = $portfolio->getNext()) {
			$data['nextItem'] = Url::to(['ajax/portfolio-item', 'id' => $next->id]);
		}
		return $this->renderJson($data);
	}
}

protected/controllers/BaseController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Page;
use yii\web\HttpException;

class BaseController extends Controller {

	public $enableCsrfValidation = false;
	public $layout = 'main';

	/**
	 * Makes array data to view as JSON
	 *
	 * @param array $data
	 * @return string
	 */
	public function renderJson(array $data) {
		header('Content-Type: application/json; charset=utf-8');
		return json_encode($data, defined('JSON_UNESCAPED_UNICODE')? JSON_UNESCAPED_UNICODE: 0);
	}

	protected function renderContentPage($url) {
		$page = Page::find()->byUrl($url)->one();

		if (!$page) {
			throw new HttpException(404, Yii::t('yii', 'Page not found.'));
		}
		return $this->render('page', [
			'page' => $page
		]);
	}
}

protected/controllers/MainController.php
<?php

namespace app\controllers;

use app\models\ContactForm;
use app\models\Portfolio;
use Yii;

class MainController extends BaseController {

	public function actions() {
		return [
			'error'   => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class'           => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST? 'testme': null,
			],
		];
	}

	public function actionIndex() {
		$portfolio = Portfolio::find()->one();
		return $this->render('index', [
			'portfolio' => $portfolio,
		]);
	}

	public function actionAbout() {
		$this->view->title = 'О веб-студии';
		return $this->render('about');
	}

	public function actionServices() {
		$this->view->title = 'Наши услуги';
		return $this->render('services');
	}

	public function actionContacts() {
		$this->view->title = 'Связь с нами';

		$model = new ContactForm();

		if (Yii::$app->request->isPost) {
			$model->load(Yii::$app->request->post());
			Yii::$app->session->setFlash('contacts', $model->sendAdminEmail());
		}

		return $this->render('contacts', [
			'model' => $model
		]);
	}
}

protected/views/layouts/main.php
<?php
use yii\helpers\Html;

use app\widgets\Nav;
use app\assets\AppAsset;
use yii\helpers\Url;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);

$action = Yii::$app->controller->action->id;
?>
<?php $this->beginPage() ?>
	<!DOCTYPE html>
	<html lang="<?= Yii::$app->language ?>">
	<head>
		<meta charset="<?= Yii::$app->charset ?>">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="Разработка, создание и поддержка сайтов - веб студия Tetris Lab">
		<link rel="icon" type="image/x-icon" href="/images/favicon.jpg">
		<?= Html::csrfMetaTags() ?>
		<title><?= Html::encode($this->title) ?> - Tetris Lab</title>
		<?php $this->head() ?>
	</head>
	<body>
	<?php $this->beginBody() ?>

	<div class="body">
		<header>
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<a href="/" class="logo"></a>
					</div>
					<div class="col-sm-8">
						<?php
						$actionId = Yii::$app->controller->action->id;
						echo Nav::widget([
							'options' => ['class' => 'menu-nav'],
							'items'   => [
								[
									'label'  => 'О нас',
									'url'    => ['main/about'],
									'active' => $actionId == 'about',
								],
								[
									'label'  => 'Услуги',
									'url'    => ['main/services'],
									'active' => $actionId == 'services',
								],
								[
									'label'  => 'Контакты',
									'url'    => ['main/contacts'],
									'active' => $actionId == 'contacts',
								],
							]
						]) ?>
					</div>
				</div>
			</div>
		</header>
		<div class="container">
			<section class="content-wrapper">
				<h1 class="page-title"><?= $this->title ?></h1>
				<div class="content" id="content">
					<?= $content ?>
				</div>
			</section>
		</div>
		<footer>
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						&copy; Tetris Lab Studio <?= date('Y') ?>
					</div>
				</div>
			</div>
		</footer>
	</div>
	<?php $this->endBody() ?>
	</body>
	</html>
<?php $this->endPage() ?>

protected/views/main/about.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

/**
 * @var $this      yii\web\View
 */
?>

<p>Tetris Lab&nbsp;— это&nbsp;команда молодых профессионалов в&nbsp;области веб-разработки. Мы&nbsp;не&nbsp;будем
	здесь описывать, что&nbsp;мы&nbsp;делаем сайты лучше всех, просто опишем условия
	работы с&nbsp;нами.</p>
<p>Этапы работы:</p>
<ul>
	<li>Техническое задание. "Как, зачем и почему" будет работать ваш сайт, какие задачи решает, какие эффекты и фичи будут использованы.
		Любой функционал, не указанный в ТЗ, будет делаться за отдельную плату
	</li>
	<li>Расчет стоимости и сроков сдачи проекта</li>
	<li><a href="<?= Url::to(['main/services']) ?>">Разработка</a> дизайна сайта на основе ТЗ.
		Клиент взаимодействует с дизайнером для конвертации "картинки из головы" в реальные макеты</li>
	<li>Верстка и&nbsp;сборка сайта на&nbsp;CMS (систему управления контентом). Мы работаем с Bitrix,
		однако реализовать сайт мы можем и на бесплатном "движке", все зависит от проекта и пожеланий клиента</li>
</ul>

<p>Основной приоритет нашей команды&nbsp;— полная прозрачность работы для&nbsp;заказчика.
	Проект в процессе разработки будет доступен для просмотра заказчиком.</p>
<p>В своей работе мы&nbsp;используем последние технологии веб-разработки, потому что стремимся создать быстрое
	и нересурсоемкое приложение, дабы спасти и клиента от мучительного ожидания загрузки страницы, и ваши ресурсы вашего сервера.
	Мы делаем адаптивные сайты, т.е. удобные для просмотра на любых разрешениях экрана и любых девайсах,
	поэтому нет нужды делать всякие отдельные мобильные версии сайта.
</p>
<p>
	Не нужно ломать голову, просто <a href="<?= Url::to(['main/contacts']) ?>">напиши нам</a>, и уже полдела сделано.
</p>
<div class="inner-cube1">&nbsp;</div>

protected/views/main/contacts.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

/**
 * @var $this  yii\web\View
 * @var $model \app\models\ContactForm
 * @var $form  yii\bootstrap\ActiveForm
 */
$flash = Yii::$app->session->getFlash('contacts');
?>

<?php /*<p>Телефон: <nobr>+7 (902) 528-62-98</nobr></p>*/ ?>

<?php if ($flash !== null) {
	echo Html::tag('div', $flash? 'Сообщение отправлено. Скоро мы свяжемся с вами': 'Ошибка', ['class' => 'alert alert-' . ($flash? 'success': 'danger')]);
}
?>
<?php $form = ActiveForm::begin([
	'id'          => 'contact-form',
	'fieldConfig' => [
		'template' => "<div class=\"row\"><div class=\"col-sm-4\">{label}</div>\n<div class=\"col-sm-8\">{input}{error}</div></div>",
	],
]); ?>
<?= $form->field($model, 'name') ?>
<?= $form->field($model, 'email') ?>
<?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>
<?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
	'captchaAction' => 'main/captcha',
	'template'      => '<div class="row"><div class="col-sm-4">{image}</div><div class="col-sm-8">{input}</div></div>',
]) ?>
<div class="form-group text-center">
	<?= Html::submitButton('Отправить', ['class' => 'btn btn-lg btn-primary', 'name' => 'contact-button']) ?>
</div>
<?php ActiveForm::end(); ?>

<div class="inner-cube2"></div>

protected/views/main/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

protected/views/main/index.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

/**
 * @var $this      yii\web\View
 * @var $portfolio \app\models\Portfolio
 */
$this->title = 'Разработка и создание сайтов для людей';
$this->registerJsFile('/js/index.js', ['depends' => ['yii\web\JqueryAsset', 'app\assets\BowerAsset']]);
?>
<div id="portfolio-init" data-url="<?= Url::to(['ajax/portfolio-item', 'id' => $portfolio->id]) ?>"></div>

protected/views/main/page.php
<?php
use yii\helpers\Html;

/**
 * @var $this yii\web\View
 * @var $page \app\models\Page
 */

echo $page->content;

protected/views/main/services.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

/**
 * @var $this      yii\web\View
 */
?>

<p>Мы&nbsp;оказываем услуги по&nbsp;следующим направлениям:</p>
<ul>
	<li>создание сайтов &laquo;под ключ&raquo;</li>
	<li>продвижение сайтов в&nbsp;поисковых системах и&nbsp;размещение контекстной рекламы</li>
	<li>поддержка и&nbsp;администрирование существующих сайтов</li>
</ul>
<h3>Создание сайта &laquo;под ключ&raquo;</h3>
<p> Мы&nbsp;нарисуем красивый дизайн. Сверстаем так, чтобы сайт корректно отображался на&nbsp;любых устройствах,
	разрешениях и&nbsp;браузерах. Интегрируем все это на&nbsp;<acronym title="Content management system"
	lang="en">CMS</acronym>. И&nbsp;все. Стоимость высчитывается индивидуально после получения ТЗ, но&nbsp;мы&nbsp;гарантируем, цена вас приятно удивит.
</p>
<h3>Продвижение сайта</h3>
<p>Мы&nbsp;подберем для вашего сайта популярные поисковые запросы. Выведем ваш сайт в&nbsp;топ10 Яндекса и&nbsp;Гугла по&nbsp;ключевым
	запросам. Получим неиссякаемый потом потенциальных клиентов
</p>
<h3>Поддержка сайтов</h3>
<p>У&nbsp;вас есть рабочий сайт? Тогда мы&nbsp;готовы заниматься его поддержкой, развитием
	и&nbsp;администрированием.</p>

<h3>Что делать?</h3>
<p>Оставить заявку на&nbsp;любую из&nbsp;услуг вы&nbsp;можете в&nbsp;нашей <a href="<?= Url::to(['main/contacts']) ?>">форме
		обратной связи</a>.</p>